version: 2

sources:
  - name: mysql_rds_sakila
    database: sakila_raw
    tables:
      - name: actor
      - name: address
      - name: store
      - name: staff
      - name: customer
      - name: city
      - name: country
